services:
  db-mysql:
    image: mysql
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
      - ./:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 15s
      timeout: 20s
      retries: 10
    networks:
      - service-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    environment:
      PMA_HOSTS: db-mysql
      PMA_PORT: 3307
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - service-network

  backend:
    container_name: backend
    build: .
    volumes:
      - ./:/app
    environment:
      DATABASE_URL: mysql+pymysql://root:root@db-mysql:3307/db_book
    ports:
      - "8000:8000"
    depends_on:
      - db-mysql
    networks:
      - service-network

  migration:
    container_name: migration
    build:
      context: .
      dockerfile: Dockerfile
    command: alembic upgrade head
    depends_on:
      db-mysql:
        condition: service_healthy

volumes:
  mysql-data:

networks:
  service-network:
    driver: bridge
